hystrix:
  command:
    default: #全局配置，如果要配置某个类，即feignclient#method(param)
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    OrderServiceFeignClient#getOrder(Integer):
      execution:
        isolation:
          #基于信号量隔离的策略
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 10
    OrderServiceFeignClient#insert(Integer):
      execution:
        isolation:
          #基于线程隔离的策略
          strategy: THREAD
  threadpool:
    order-service:
      coreSize: 2
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: refresh,hystrix.stream
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_mall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: META-INF/locale/messages
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
mybatis:
  type-aliases-package: priv.fandeshan.demo.ribbonuserservice.mapper.entitys
  config-location: classpath:/mybatis-config.xml
